### ISSUE TITLE
Input filtering for completed work

### ISSUE THREAD

**Issue by amitschang** [ssec-jhu/bluephos#43]
To prevent from repeated work, an option to filter the input list of ligands based on output tables is desired. It should be possible to electively use this filtering, as in some cases it may be desired to run early steps again (e.g. in case of config/model changes).

```sh
python -m bluephos.bluephos_pipeline --input-filter-reference /path/to/table [other options, ...] 
```

is a possible implementation

**Comment by xiangchenjhu** [comment]
This feature was included in #67
