### ISSUE TITLE
Pass orca MPI options for scheduling within ray

### ISSUE THREAD

**Issue by amitschang** [ssec-jhu/bluephos#93]
In a slurm environment the MPI might be built to schedule against slurm, which ends up not working well with ray since it manages the scheduling of tasks within its system. We have found that the following options can help ensure scheduling proceeds as expected:

```py
task_host = socket.gethostname()
mpi_options = f"--host {task_host} --oversubscribe"
```

These can be passed to ORCA. Basically it says we want to run on the host ray scheduled, and we want to use the requested number of CPUs, even if MPI doesn't see them that way (e.g. with hyperthreading).

I think these options are probably work and are useful even without slurm

**Comment by xiangchenjhu** [comment]
addressed in #100
